## Desarrollo
DES/host:172.16.64.16
DES/port:1530
DES/sid:LBDR.BATERA.LANBIDE.EUS
DES/1/user:flb
DES/0/user:flbpru
DES/1/pass:flb
DES/0/pass:flbpru
## Preproduccion
PRE/host:vej22rac01pr-scan.batera.lanbide.eus
PRE/port:1530
PRE/sid:EJLBPR.BATERA.LANBIDE.EUS
PRE/1/user:flb
PRE/0/user:flbpru
PRE/1/pass:pruebafb
PRE/0/pass:pruebafu
## Produccion
PRO/host:vej22rac01p-scan.batera.lanbide.eus
PRO/port:1530
PRO/sid:EJLBR.BATERA.LANBIDE.EUS
PRO/1/user:flb
PRO/0/user:flbpru
PRO/1/pass:
PRO/0/pass:
